import type { AttributeDefinition } from "../types";

export const defaultAttributes: AttributeDefinition[] = [
  {
    id: "attribute.finishing",
    categoryId: "attribute_category.technical",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Finishing",
      abbreviation: "FIN",
      categoryId: "attribute_category.technical",
      unit: "1_20",
      description: "Shot conversion quality in open play.",
      tags: ["technical", "attacking"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.first_touch",
    categoryId: "attribute_category.technical",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "First Touch",
      abbreviation: "1T",
      categoryId: "attribute_category.technical",
      unit: "1_20",
      description: "Control quality on first contact with the ball.",
      tags: ["technical", "ball_control"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.passing",
    categoryId: "attribute_category.technical",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Passing",
      abbreviation: "PAS",
      categoryId: "attribute_category.technical",
      unit: "1_20",
      description: "Accuracy and range selection in passing actions.",
      tags: ["technical", "distribution"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.decisions",
    categoryId: "attribute_category.mental",
    entityKinds: ["player", "coach"],
    discoverable: true,
    metadata: {
      name: "Decisions",
      abbreviation: "DEC",
      categoryId: "attribute_category.mental",
      unit: "1_20",
      description: "Decision-making quality under game pressure.",
      tags: ["mental", "game_iq"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.positioning",
    categoryId: "attribute_category.mental",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Positioning",
      abbreviation: "POS",
      categoryId: "attribute_category.mental",
      unit: "1_20",
      description: "Spatial awareness and off-ball positioning.",
      tags: ["mental", "defensive"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.vision",
    categoryId: "attribute_category.mental",
    entityKinds: ["player", "coach"],
    discoverable: true,
    metadata: {
      name: "Vision",
      abbreviation: "VIS",
      categoryId: "attribute_category.mental",
      unit: "1_20",
      description: "Ability to identify high-value passing options.",
      tags: ["mental", "creativity"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.acceleration",
    categoryId: "attribute_category.physical",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Acceleration",
      abbreviation: "ACC",
      categoryId: "attribute_category.physical",
      unit: "1_20",
      description: "Initial burst speed over short distances.",
      tags: ["physical", "speed"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.pace",
    categoryId: "attribute_category.physical",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Pace",
      abbreviation: "PAC",
      categoryId: "attribute_category.physical",
      unit: "1_20",
      description: "Top-end speed sustainability.",
      tags: ["physical", "speed"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.stamina",
    categoryId: "attribute_category.physical",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Stamina",
      abbreviation: "STA",
      categoryId: "attribute_category.physical",
      unit: "1_20",
      description: "Capacity to sustain intensity across match duration.",
      tags: ["physical", "endurance"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "attribute.command_of_area",
    categoryId: "attribute_category.goalkeeping",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Command of Area",
      abbreviation: "COA",
      categoryId: "attribute_category.goalkeeping",
      unit: "1_20",
      description: "Goalkeeper command in aerial and crowded situations.",
      tags: ["goalkeeping", "aerial"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
];

export function getAttributeById(id: AttributeDefinition["id"]): AttributeDefinition | undefined {
  return defaultAttributes.find((attribute) => attribute.id === id);
}

export function listAttributesByCategory(
  categoryId: AttributeDefinition["categoryId"],
): AttributeDefinition[] {
  return defaultAttributes.filter((attribute) => attribute.categoryId === categoryId);
}
