import type { MetricDefinition } from "../types";

export const defaultMetrics: MetricDefinition[] = [
  {
    id: "metric.goals_per90",
    categoryId: "metric_category.output",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Goals per 90",
      abbreviation: "G/90",
      categoryId: "metric_category.output",
      unit: "per90",
      description: "Non-penalty goals scored per 90 minutes.",
      tags: ["output", "attacking"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.assists_per90",
    categoryId: "metric_category.output",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Assists per 90",
      abbreviation: "A/90",
      categoryId: "metric_category.output",
      unit: "per90",
      description: "Assists produced per 90 minutes.",
      tags: ["output", "creation"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.xg_per90",
    categoryId: "metric_category.chance_quality",
    entityKinds: ["player", "club"],
    discoverable: true,
    metadata: {
      name: "Expected Goals per 90",
      abbreviation: "xG/90",
      categoryId: "metric_category.chance_quality",
      unit: "per90",
      description: "Expected goals generated per 90 minutes.",
      tags: ["chance_quality", "attacking"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.xa_per90",
    categoryId: "metric_category.chance_quality",
    entityKinds: ["player", "club"],
    discoverable: true,
    metadata: {
      name: "Expected Assists per 90",
      abbreviation: "xA/90",
      categoryId: "metric_category.chance_quality",
      unit: "per90",
      description: "Expected assists generated per 90 minutes.",
      tags: ["chance_quality", "creation"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.key_passes_per90",
    categoryId: "metric_category.progression",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Key Passes per 90",
      abbreviation: "KP/90",
      categoryId: "metric_category.progression",
      unit: "per90",
      description: "Shot-creating passes per 90 minutes.",
      tags: ["progression", "creation"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.pass_completion_pct",
    categoryId: "metric_category.distribution",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "Pass Completion",
      abbreviation: "Pass%",
      categoryId: "metric_category.distribution",
      unit: "percent",
      description: "Completed passes as percentage of attempted passes.",
      tags: ["distribution", "retention"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.duel_win_pct",
    categoryId: "metric_category.defensive",
    entityKinds: ["player", "club"],
    discoverable: true,
    metadata: {
      name: "Duel Win Rate",
      abbreviation: "Duel%",
      categoryId: "metric_category.defensive",
      unit: "percent",
      description: "Share of duels won over total contested duels.",
      tags: ["defensive", "physical"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.clean_sheets_pct",
    categoryId: "metric_category.defensive",
    entityKinds: ["club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Clean Sheet Rate",
      abbreviation: "CS%",
      categoryId: "metric_category.defensive",
      unit: "percent",
      description: "Matches without conceding as a percentage.",
      tags: ["defensive", "outcome"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.points_per_match",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "coach", "competition"],
    discoverable: true,
    metadata: {
      name: "Points per Match",
      abbreviation: "PPM",
      categoryId: "metric_category.outcome",
      unit: "ratio",
      description: "Points collected divided by matches played.",
      tags: ["outcome", "performance"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.minutes_played",
    categoryId: "metric_category.sample",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Minutes Played",
      abbreviation: "MIN",
      categoryId: "metric_category.sample",
      unit: "minutes",
      description: "Total minutes played in the sampled period.",
      tags: ["sample", "availability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.shots_on_target_pct",
    categoryId: "metric_category.output",
    entityKinds: ["player", "club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Shots on Target Rate",
      abbreviation: "SoT%",
      categoryId: "metric_category.output",
      unit: "percent",
      description: "Shots on target as percentage of all shots.",
      tags: ["output", "efficiency"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.pressures_per90",
    categoryId: "metric_category.defensive",
    entityKinds: ["player", "club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Pressures per 90",
      abbreviation: "Press/90",
      categoryId: "metric_category.defensive",
      unit: "per90",
      description: "Defensive pressure actions per 90 minutes.",
      tags: ["defensive", "intensity"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.progressive_passes_per90",
    categoryId: "metric_category.progression",
    entityKinds: ["player", "club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Progressive Passes per 90",
      abbreviation: "ProgP/90",
      categoryId: "metric_category.progression",
      unit: "per90",
      description: "Forward-value passes per 90 minutes.",
      tags: ["progression", "possession"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.possession_pct",
    categoryId: "metric_category.distribution",
    entityKinds: ["club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Possession Share",
      abbreviation: "Poss%",
      categoryId: "metric_category.distribution",
      unit: "percent",
      description: "Average possession percentage.",
      tags: ["distribution", "control"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.goals_conceded_per90",
    categoryId: "metric_category.defensive",
    entityKinds: ["club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Goals Conceded per 90",
      abbreviation: "GA/90",
      categoryId: "metric_category.defensive",
      unit: "per90",
      description: "Goals conceded per 90 minutes.",
      tags: ["defensive", "outcome"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.goals_scored_per90",
    categoryId: "metric_category.output",
    entityKinds: ["club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Goals Scored per 90",
      abbreviation: "GF/90",
      categoryId: "metric_category.output",
      unit: "per90",
      description: "Goals scored per 90 minutes.",
      tags: ["output", "attack"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.expected_points_per_match",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Expected Points per Match",
      abbreviation: "xPPM",
      categoryId: "metric_category.outcome",
      unit: "ratio",
      description: "Model-based expected points per match.",
      tags: ["outcome", "quality"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.youth_minutes_pct",
    categoryId: "metric_category.sample",
    entityKinds: ["club", "coach", "country", "competition"],
    discoverable: true,
    metadata: {
      name: "Youth Minutes Share",
      abbreviation: "U23%",
      categoryId: "metric_category.sample",
      unit: "percent",
      description: "Share of minutes played by youth players.",
      tags: ["sample", "development"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.transfer_profit_ratio",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "country"],
    discoverable: true,
    metadata: {
      name: "Transfer Profit Ratio",
      abbreviation: "TPR",
      categoryId: "metric_category.outcome",
      unit: "ratio",
      description: "Transfer profit relative to transfer spend.",
      tags: ["finance", "market"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.financial_strength_index",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Financial Strength Index",
      abbreviation: "FSI",
      categoryId: "metric_category.outcome",
      unit: "0_100",
      description: "Composite financial resilience score.",
      tags: ["finance", "stability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.reputation_index",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "competition", "country", "coach"],
    discoverable: true,
    metadata: {
      name: "Reputation Index",
      abbreviation: "REP",
      categoryId: "metric_category.outcome",
      unit: "0_100",
      description: "Composite reputation indicator.",
      tags: ["prestige", "status"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.tactical_flexibility_index",
    categoryId: "metric_category.progression",
    entityKinds: ["coach", "club", "competition"],
    discoverable: true,
    metadata: {
      name: "Tactical Flexibility Index",
      abbreviation: "TFI",
      categoryId: "metric_category.progression",
      unit: "0_100",
      description: "Ability to sustain performance across tactical shapes.",
      tags: ["tactics", "adaptability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.cup_win_rate",
    categoryId: "metric_category.outcome",
    entityKinds: ["coach", "club", "country"],
    discoverable: true,
    metadata: {
      name: "Cup Win Rate",
      abbreviation: "Cup%",
      categoryId: "metric_category.outcome",
      unit: "percent",
      description: "Share of cup campaigns won.",
      tags: ["outcome", "cups"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.championship_win_rate",
    categoryId: "metric_category.outcome",
    entityKinds: ["coach", "club", "country"],
    discoverable: true,
    metadata: {
      name: "Championship Win Rate",
      abbreviation: "League%",
      categoryId: "metric_category.outcome",
      unit: "percent",
      description: "Share of league campaigns won.",
      tags: ["outcome", "league"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.academy_output_index",
    categoryId: "metric_category.sample",
    entityKinds: ["club", "coach", "country", "competition"],
    discoverable: true,
    metadata: {
      name: "Academy Output Index",
      abbreviation: "AOI",
      categoryId: "metric_category.sample",
      unit: "0_100",
      description: "Output quality of developed youth players.",
      tags: ["development", "academy"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.player_sales_per_season",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "country"],
    discoverable: true,
    metadata: {
      name: "Player Sales per Season",
      abbreviation: "Sales/S",
      categoryId: "metric_category.outcome",
      unit: "count",
      description: "Average number of outbound player sales per season.",
      tags: ["market", "exports"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.player_purchases_per_season",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "country"],
    discoverable: true,
    metadata: {
      name: "Player Purchases per Season",
      abbreviation: "Buys/S",
      categoryId: "metric_category.outcome",
      unit: "count",
      description: "Average number of inbound player purchases per season.",
      tags: ["market", "imports"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.continental_points",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Continental Points",
      abbreviation: "CP",
      categoryId: "metric_category.outcome",
      unit: "points",
      description: "Points accumulated in continental competitions.",
      tags: ["continental", "prestige"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.title_count_index",
    categoryId: "metric_category.outcome",
    entityKinds: ["club", "coach", "country", "competition"],
    discoverable: true,
    metadata: {
      name: "Title Count Index",
      abbreviation: "TCI",
      categoryId: "metric_category.outcome",
      unit: "0_100",
      description: "Normalized index of historical titles.",
      tags: ["history", "legacy"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.coach_win_rate",
    categoryId: "metric_category.outcome",
    entityKinds: ["coach"],
    discoverable: true,
    metadata: {
      name: "Coach Win Rate",
      abbreviation: "W%",
      categoryId: "metric_category.outcome",
      unit: "percent",
      description: "Share of wins in coached matches.",
      tags: ["coach", "outcome"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.coach_goal_diff_per90",
    categoryId: "metric_category.outcome",
    entityKinds: ["coach"],
    discoverable: true,
    metadata: {
      name: "Coach Goal Difference per 90",
      abbreviation: "GD/90",
      categoryId: "metric_category.outcome",
      unit: "per90",
      description: "Goal difference per 90 under the coach.",
      tags: ["coach", "performance"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.coach_youth_integration_pct",
    categoryId: "metric_category.sample",
    entityKinds: ["coach"],
    discoverable: true,
    metadata: {
      name: "Coach Youth Integration",
      abbreviation: "YI%",
      categoryId: "metric_category.sample",
      unit: "percent",
      description: "Share of youth minutes under the coach.",
      tags: ["coach", "development"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.coach_trophy_index",
    categoryId: "metric_category.outcome",
    entityKinds: ["coach"],
    discoverable: true,
    metadata: {
      name: "Coach Trophy Index",
      abbreviation: "CTI",
      categoryId: "metric_category.outcome",
      unit: "0_100",
      description: "Composite coach trophy and finals index.",
      tags: ["coach", "titles"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.country_exports_per_season",
    categoryId: "metric_category.outcome",
    entityKinds: ["country"],
    discoverable: true,
    metadata: {
      name: "Country Exports per Season",
      abbreviation: "EXP/S",
      categoryId: "metric_category.outcome",
      unit: "count",
      description: "Players exported abroad per season.",
      tags: ["country", "exports"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.country_talent_depth_index",
    categoryId: "metric_category.sample",
    entityKinds: ["country"],
    discoverable: true,
    metadata: {
      name: "Country Talent Depth Index",
      abbreviation: "TDI",
      categoryId: "metric_category.sample",
      unit: "0_100",
      description: "Depth of high-potential player pool.",
      tags: ["country", "talent"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.competition_balance_index",
    categoryId: "metric_category.outcome",
    entityKinds: ["competition"],
    discoverable: true,
    metadata: {
      name: "Competition Balance Index",
      abbreviation: "CBI",
      categoryId: "metric_category.outcome",
      unit: "0_100",
      description: "Title race and points distribution balance.",
      tags: ["competition", "balance"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "metric.competition_surprise_index",
    categoryId: "metric_category.outcome",
    entityKinds: ["competition"],
    discoverable: true,
    metadata: {
      name: "Competition Surprise Index",
      abbreviation: "CSI",
      categoryId: "metric_category.outcome",
      unit: "0_100",
      description: "Frequency of upset outcomes and unexpected runs.",
      tags: ["competition", "variance"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
];

export function getMetricById(id: MetricDefinition["id"]): MetricDefinition | undefined {
  return defaultMetrics.find((metric) => metric.id === id);
}

export function listMetricsByCategory(
  categoryId: MetricDefinition["categoryId"],
): MetricDefinition[] {
  return defaultMetrics.filter((metric) => metric.categoryId === categoryId);
}
