import type { ContextDefinition } from "../types";

export const defaultContexts: ContextDefinition[] = [
  {
    id: "context.league_strength",
    categoryId: "context_category.competition",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "League Strength",
      abbreviation: "LSTR",
      categoryId: "context_category.competition",
      unit: "0_100",
      description: "Relative strength of the league where data was collected.",
      tags: ["competition", "difficulty"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.match_importance",
    categoryId: "context_category.match",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "Match Importance",
      abbreviation: "MIMP",
      categoryId: "context_category.match",
      unit: "0_100",
      description: "Importance weighting of matches in the sampled period.",
      tags: ["match", "pressure"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.home_away_balance",
    categoryId: "context_category.schedule",
    entityKinds: ["player", "club"],
    discoverable: true,
    metadata: {
      name: "Home-Away Balance",
      abbreviation: "HAB",
      categoryId: "context_category.schedule",
      unit: "0_100",
      description: "Balance between home and away exposure in sampled games.",
      tags: ["schedule", "bias"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.fixture_congestion",
    categoryId: "context_category.schedule",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "Fixture Congestion",
      abbreviation: "FCG",
      categoryId: "context_category.schedule",
      unit: "0_100",
      description: "Density of fixtures across the observed timeframe.",
      tags: ["schedule", "load"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.squad_stability",
    categoryId: "context_category.team_state",
    entityKinds: ["club", "coach"],
    discoverable: true,
    metadata: {
      name: "Squad Stability",
      abbreviation: "SST",
      categoryId: "context_category.team_state",
      unit: "0_100",
      description: "Continuity level of squad and tactical core.",
      tags: ["team_state", "continuity"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.opponent_quality",
    categoryId: "context_category.competition",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "Opponent Quality",
      abbreviation: "OPQ",
      categoryId: "context_category.competition",
      unit: "0_100",
      description: "Average quality of opponents in sampled matches.",
      tags: ["competition", "difficulty"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.age",
    categoryId: "context_category.player_state",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Age Context",
      abbreviation: "AGE",
      categoryId: "context_category.player_state",
      unit: "years",
      description: "Age-related context impact over performance interpretation.",
      tags: ["player_state", "development"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.minutes",
    categoryId: "context_category.sample",
    entityKinds: ["player", "club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Minutes Context",
      abbreviation: "MIN",
      categoryId: "context_category.sample",
      unit: "minutes",
      description: "Sample size context based on minutes available.",
      tags: ["sample", "reliability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.team_strength",
    categoryId: "context_category.team_state",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "Team Strength",
      abbreviation: "TSTR",
      categoryId: "context_category.team_state",
      unit: "0_100",
      description: "Overall team quality level around sampled performances.",
      tags: ["team_state", "quality"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.competition_reputation",
    categoryId: "context_category.competition",
    entityKinds: ["player", "club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Competition Reputation",
      abbreviation: "CREP",
      categoryId: "context_category.competition",
      unit: "0_100",
      description: "Prestige and quality level of the active competition.",
      tags: ["competition", "prestige"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.continental_strength",
    categoryId: "context_category.competition",
    entityKinds: ["club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Continental Strength",
      abbreviation: "CSTR",
      categoryId: "context_category.competition",
      unit: "0_100",
      description: "Relative continental ecosystem strength.",
      tags: ["continental", "quality"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.economic_context",
    categoryId: "context_category.environment",
    entityKinds: ["club", "country", "competition"],
    discoverable: true,
    metadata: {
      name: "Economic Context",
      abbreviation: "ECON",
      categoryId: "context_category.environment",
      unit: "0_100",
      description: "Economic capacity context for squad building and retention.",
      tags: ["environment", "finance"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.talent_pool_depth",
    categoryId: "context_category.environment",
    entityKinds: ["country", "competition", "club"],
    discoverable: true,
    metadata: {
      name: "Talent Pool Depth",
      abbreviation: "TPD",
      categoryId: "context_category.environment",
      unit: "0_100",
      description: "Depth of available talent in the environment.",
      tags: ["environment", "talent"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.fixture_difficulty",
    categoryId: "context_category.schedule",
    entityKinds: ["club", "coach", "competition"],
    discoverable: true,
    metadata: {
      name: "Fixture Difficulty",
      abbreviation: "FDIFF",
      categoryId: "context_category.schedule",
      unit: "0_100",
      description: "Difficulty level of the fixture sequence.",
      tags: ["schedule", "difficulty"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.era_weight",
    categoryId: "context_category.environment",
    entityKinds: ["club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Era Weight",
      abbreviation: "ERA",
      categoryId: "context_category.environment",
      unit: "0_100",
      description: "Weighting factor by historical era comparability.",
      tags: ["history", "normalization"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "context.governance_stability",
    categoryId: "context_category.environment",
    entityKinds: ["club", "country", "competition"],
    discoverable: true,
    metadata: {
      name: "Governance Stability",
      abbreviation: "GOV",
      categoryId: "context_category.environment",
      unit: "0_100",
      description: "Institutional and governance stability around the entity.",
      tags: ["environment", "stability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
];

export function getContextById(id: ContextDefinition["id"]): ContextDefinition | undefined {
  return defaultContexts.find((context) => context.id === id);
}

export function listContextsByCategory(
  categoryId: ContextDefinition["categoryId"],
): ContextDefinition[] {
  return defaultContexts.filter((context) => context.categoryId === categoryId);
}
