import type { ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

function clubScore(args: {
  id: ScoreDefinition["id"];
  name: string;
  categoryId: ScoreDefinition["categoryId"];
  metrics: ReturnType<typeof mr>[];
  contexts: ReturnType<typeof cr>[];
  modifiers: ReturnType<typeof mor>[];
  description: string;
}): ScoreDefinition {
  return {
    id: args.id,
    name: args.name,
    entityKind: "club",
    categoryId: args.categoryId,
    description: args.description,
    metricRefs: args.metrics,
    contextRefs: args.contexts,
    modifierRefs: args.modifiers,
    status: "active",
    version: "1.0.0",
    metadata: { source: "score-library.phase-1.4b", discoverable: true },
  };
}

const clubContexts = [
  cr("context.league_strength", 1),
  cr("context.competition_reputation", 0.9),
  cr("context.team_strength", 1),
  cr("context.fixture_difficulty", 0.8),
  cr("context.governance_stability", 0.8),
];
const clubModifiers = [
  mor("modifier.consistency", 1),
  mor("modifier.big_matches", 0.9),
  mor("modifier.momentum_boost", 0.8),
  mor("modifier.debt_pressure", 0.8),
  mor("modifier.data_quality_flag", 0.8),
];

export const clubScoreDefinitions: ScoreDefinition[] = [
  clubScore({
    id: "score.club_offensive",
    name: "Clube Ofensivo",
    categoryId: "score_category.club_style",
    description: "Attack-oriented output profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.4),
      mr("metric.xg_per90", 1.2),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.progressive_passes_per90", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_defensive",
    name: "Clube Defensivo",
    categoryId: "score_category.club_style",
    description: "Defensive solidity profile.",
    metrics: [
      mr("metric.goals_conceded_per90", 1.4),
      mr("metric.clean_sheets_pct", 1.2),
      mr("metric.duel_win_pct", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_possession",
    name: "Clube de Posse",
    categoryId: "score_category.club_style",
    description: "Ball-control and circulation profile.",
    metrics: [
      mr("metric.possession_pct", 1.4),
      mr("metric.pass_completion_pct", 1.3),
      mr("metric.progressive_passes_per90", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_transition",
    name: "Clube de Transicao",
    categoryId: "score_category.club_style",
    description: "Transition and directness profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.2),
      mr("metric.pressures_per90", 1.1),
      mr("metric.xg_per90", 1),
      mr("metric.shots_on_target_pct", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_technical",
    name: "Clube Tecnico",
    categoryId: "score_category.club_style",
    description: "Technical execution profile.",
    metrics: [
      mr("metric.pass_completion_pct", 1.3),
      mr("metric.progressive_passes_per90", 1.1),
      mr("metric.xa_per90", 1),
      mr("metric.possession_pct", 0.9),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_physical",
    name: "Clube Fisico",
    categoryId: "score_category.club_style",
    description: "Physical duel and intensity profile.",
    metrics: [
      mr("metric.duel_win_pct", 1.4),
      mr("metric.pressures_per90", 1.1),
      mr("metric.goals_conceded_per90", 0.9),
      mr("metric.points_per_match", 0.8),
      mr("metric.clean_sheets_pct", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_developer",
    name: "Clube Formador",
    categoryId: "score_category.club_development",
    description: "Youth development and pathway profile.",
    metrics: [
      mr("metric.academy_output_index", 1.3),
      mr("metric.youth_minutes_pct", 1.2),
      mr("metric.player_sales_per_season", 1),
      mr("metric.transfer_profit_ratio", 0.9),
      mr("metric.points_per_match", 0.7),
    ],
    contexts: [...clubContexts, cr("context.talent_pool_depth", 0.9)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_buyer",
    name: "Clube Comprador",
    categoryId: "score_category.club_market",
    description: "Active inbound market profile.",
    metrics: [
      mr("metric.player_purchases_per_season", 1.4),
      mr("metric.financial_strength_index", 1.1),
      mr("metric.reputation_index", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: [...clubContexts, cr("context.economic_context", 0.9)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_seller",
    name: "Clube Vendedor",
    categoryId: "score_category.club_market",
    description: "Talent export and value extraction profile.",
    metrics: [
      mr("metric.player_sales_per_season", 1.3),
      mr("metric.transfer_profit_ratio", 1.2),
      mr("metric.academy_output_index", 1),
      mr("metric.financial_strength_index", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: [...clubContexts, cr("context.economic_context", 0.9)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_breakout",
    name: "Clube Revelacao",
    categoryId: "score_category.club_results",
    description: "Breakout season and overperformance profile.",
    metrics: [
      mr("metric.competition_surprise_index", 1.2),
      mr("metric.points_per_match", 1.1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.goals_scored_per90", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: clubContexts,
    modifiers: [...clubModifiers, mor("modifier.momentum_boost", 1)],
  }),
  clubScore({
    id: "score.club_historic",
    name: "Clube Historico",
    categoryId: "score_category.club_historical",
    description: "Legacy and historic prestige profile.",
    metrics: [
      mr("metric.title_count_index", 1.4),
      mr("metric.reputation_index", 1.3),
      mr("metric.continental_points", 1),
      mr("metric.financial_strength_index", 0.8),
      mr("metric.points_per_match", 0.7),
    ],
    contexts: [...clubContexts, cr("context.era_weight", 0.9)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_dominant",
    name: "Clube Dominante",
    categoryId: "score_category.club_results",
    description: "Sustained domestic dominance profile.",
    metrics: [
      mr("metric.points_per_match", 1.4),
      mr("metric.championship_win_rate", 1.2),
      mr("metric.expected_points_per_match", 1),
      mr("metric.goals_scored_per90", 0.9),
      mr("metric.goals_conceded_per90", 0.9),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_european",
    name: "Clube Europeu",
    categoryId: "score_category.club_results",
    description: "Continental consistency and output profile.",
    metrics: [
      mr("metric.continental_points", 1.4),
      mr("metric.reputation_index", 1.2),
      mr("metric.points_per_match", 1),
      mr("metric.expected_points_per_match", 0.9),
      mr("metric.title_count_index", 0.8),
    ],
    contexts: [...clubContexts, cr("context.continental_strength", 0.9)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_financially_strong",
    name: "Clube Financeiramente Forte",
    categoryId: "score_category.club_finance",
    description: "Financial resilience and spending power profile.",
    metrics: [
      mr("metric.financial_strength_index", 1.4),
      mr("metric.transfer_profit_ratio", 1),
      mr("metric.reputation_index", 1),
      mr("metric.player_purchases_per_season", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: [...clubContexts, cr("context.economic_context", 1)],
    modifiers: clubModifiers,
  }),

  clubScore({
    id: "score.club_counter_attacking",
    name: "Clube de Contra-Ataque",
    categoryId: "score_category.club_style",
    description: "Fast transition and direct threat profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.2),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.pressures_per90", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.goals_conceded_per90", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_pressing",
    name: "Clube de Pressao",
    categoryId: "score_category.club_style",
    description: "High pressing intensity profile.",
    metrics: [
      mr("metric.pressures_per90", 1.4),
      mr("metric.duel_win_pct", 1.1),
      mr("metric.goals_scored_per90", 0.9),
      mr("metric.goals_conceded_per90", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_balanced",
    name: "Clube Equilibrado",
    categoryId: "score_category.club_style",
    description: "Balanced attack-defense profile.",
    metrics: [
      mr("metric.points_per_match", 1.2),
      mr("metric.expected_points_per_match", 1.2),
      mr("metric.goals_scored_per90", 1),
      mr("metric.goals_conceded_per90", 1),
      mr("metric.pass_completion_pct", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_cup_specialist",
    name: "Clube Taceiro",
    categoryId: "score_category.club_results",
    description: "Cup competition specialist profile.",
    metrics: [
      mr("metric.cup_win_rate", 1.4),
      mr("metric.points_per_match", 1),
      mr("metric.reputation_index", 0.9),
      mr("metric.goals_scored_per90", 0.8),
      mr("metric.goals_conceded_per90", 0.8),
    ],
    contexts: clubContexts,
    modifiers: [...clubModifiers, mor("modifier.big_matches", 1.1)],
  }),
  clubScore({
    id: "score.club_league_machine",
    name: "Maquina de Liga",
    categoryId: "score_category.club_results",
    description: "Consistency in long league campaigns.",
    metrics: [
      mr("metric.championship_win_rate", 1.4),
      mr("metric.points_per_match", 1.2),
      mr("metric.expected_points_per_match", 1),
      mr("metric.clean_sheets_pct", 0.8),
      mr("metric.goals_scored_per90", 0.8),
    ],
    contexts: clubContexts,
    modifiers: [...clubModifiers, mor("modifier.consistency", 1.1)],
  }),
  clubScore({
    id: "score.club_tactical_flexible",
    name: "Clube Taticamente Flexivel",
    categoryId: "score_category.club_style",
    description: "Tactically adaptable club profile.",
    metrics: [
      mr("metric.tactical_flexibility_index", 1.4),
      mr("metric.expected_points_per_match", 1),
      mr("metric.progressive_passes_per90", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: clubContexts,
    modifiers: [mor("modifier.versatility", 1.1), ...clubModifiers],
  }),
  clubScore({
    id: "score.club_stable_project",
    name: "Projeto Estavel",
    categoryId: "score_category.club_management",
    description: "Stable long-cycle project profile.",
    metrics: [
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.financial_strength_index", 1),
      mr("metric.academy_output_index", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: [...clubContexts, cr("context.governance_stability", 1)],
    modifiers: [mor("modifier.consistency", 1.1), ...clubModifiers],
  }),
  clubScore({
    id: "score.club_rebuilder",
    name: "Clube Reconstrutor",
    categoryId: "score_category.club_management",
    description: "Rebuild and turnover adaptation profile.",
    metrics: [
      mr("metric.tactical_flexibility_index", 1.1),
      mr("metric.player_purchases_per_season", 1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.goals_scored_per90", 0.8),
    ],
    contexts: [...clubContexts, cr("context.economic_context", 0.8)],
    modifiers: [mor("modifier.momentum_boost", 1), ...clubModifiers],
  }),
  clubScore({
    id: "score.club_declining",
    name: "Clube em Declinio",
    categoryId: "score_category.club_historical",
    description: "Legacy under performance decline profile.",
    metrics: [
      mr("metric.title_count_index", 1),
      mr("metric.reputation_index", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
      mr("metric.goals_conceded_per90", 0.9),
    ],
    contexts: [...clubContexts, cr("context.era_weight", 0.9)],
    modifiers: [mor("modifier.decline_risk", 1.2), ...clubModifiers],
  }),
  clubScore({
    id: "score.club_resurgent",
    name: "Clube em Ascensao",
    categoryId: "score_category.club_results",
    description: "Resurgent upward trajectory profile.",
    metrics: [
      mr("metric.points_per_match", 1.1),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.competition_surprise_index", 1),
      mr("metric.goals_scored_per90", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: clubContexts,
    modifiers: [mor("modifier.momentum_boost", 1.2), ...clubModifiers],
  }),
  clubScore({
    id: "score.club_global_brand",
    name: "Marca Global",
    categoryId: "score_category.club_historical",
    description: "Global brand and recognition profile.",
    metrics: [
      mr("metric.reputation_index", 1.4),
      mr("metric.financial_strength_index", 1.2),
      mr("metric.continental_points", 1),
      mr("metric.title_count_index", 0.9),
      mr("metric.points_per_match", 0.7),
    ],
    contexts: [...clubContexts, cr("context.continental_strength", 0.8)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_local_power",
    name: "Potencia Local",
    categoryId: "score_category.club_results",
    description: "Strong domestic ecosystem profile.",
    metrics: [
      mr("metric.points_per_match", 1.2),
      mr("metric.championship_win_rate", 1.1),
      mr("metric.reputation_index", 1),
      mr("metric.goals_scored_per90", 0.8),
      mr("metric.clean_sheets_pct", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_talent_hub",
    name: "Hub de Talento",
    categoryId: "score_category.club_development",
    description: "Talent concentration and development profile.",
    metrics: [
      mr("metric.academy_output_index", 1.3),
      mr("metric.youth_minutes_pct", 1),
      mr("metric.player_sales_per_season", 1),
      mr("metric.reputation_index", 0.9),
      mr("metric.financial_strength_index", 0.8),
    ],
    contexts: [...clubContexts, cr("context.talent_pool_depth", 1)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_export_machine",
    name: "Maquina Exportadora",
    categoryId: "score_category.club_market",
    description: "High frequency outbound transfer profile.",
    metrics: [
      mr("metric.player_sales_per_season", 1.4),
      mr("metric.transfer_profit_ratio", 1.2),
      mr("metric.academy_output_index", 1),
      mr("metric.youth_minutes_pct", 0.8),
      mr("metric.financial_strength_index", 0.8),
    ],
    contexts: [...clubContexts, cr("context.economic_context", 0.8)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_import_machine",
    name: "Maquina Compradora",
    categoryId: "score_category.club_market",
    description: "High frequency inbound transfer profile.",
    metrics: [
      mr("metric.player_purchases_per_season", 1.4),
      mr("metric.financial_strength_index", 1.1),
      mr("metric.reputation_index", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: [...clubContexts, cr("context.economic_context", 0.8)],
    modifiers: clubModifiers,
  }),
  clubScore({
    id: "score.club_data_driven",
    name: "Clube Data-Driven",
    categoryId: "score_category.club_management",
    description: "Data-informed optimization profile.",
    metrics: [
      mr("metric.expected_points_per_match", 1.3),
      mr("metric.tactical_flexibility_index", 1.1),
      mr("metric.progressive_passes_per90", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.financial_strength_index", 0.8),
    ],
    contexts: clubContexts,
    modifiers: [mor("modifier.data_quality_flag", 1), ...clubModifiers],
  }),
  clubScore({
    id: "score.club_underdog",
    name: "Clube Underdog",
    categoryId: "score_category.club_results",
    description: "Underdog overachievement profile.",
    metrics: [
      mr("metric.competition_surprise_index", 1.3),
      mr("metric.points_per_match", 1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.goals_scored_per90", 0.8),
      mr("metric.goals_conceded_per90", 0.8),
    ],
    contexts: [...clubContexts, cr("context.opponent_quality", 0.9)],
    modifiers: [...clubModifiers, mor("modifier.big_matches", 1)],
  }),
  clubScore({
    id: "score.club_title_chaser",
    name: "Cacador de Titulos",
    categoryId: "score_category.club_results",
    description: "High title conversion profile.",
    metrics: [
      mr("metric.title_count_index", 1.2),
      mr("metric.championship_win_rate", 1.2),
      mr("metric.cup_win_rate", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: clubContexts,
    modifiers: clubModifiers,
  }),
];
