import type { ModifierDefinition } from "../types";

export const defaultModifiers: ModifierDefinition[] = [
  {
    id: "modifier.low_minutes",
    categoryId: "modifier_category.sample",
    entityKinds: ["player"],
    discoverable: true,
    metadata: {
      name: "Low Minutes Penalty",
      abbreviation: "MIN-",
      categoryId: "modifier_category.sample",
      unit: "0_100",
      description: "Adjustment applied when minute sample is limited.",
      tags: ["sample", "confidence"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.small_sample_size",
    categoryId: "modifier_category.sample",
    entityKinds: ["player", "club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Small Sample Penalty",
      abbreviation: "SSP",
      categoryId: "modifier_category.sample",
      unit: "0_100",
      description: "Adjustment for low event/sample counts.",
      tags: ["sample", "reliability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.injury_disruption",
    categoryId: "modifier_category.availability",
    entityKinds: ["player", "club"],
    discoverable: true,
    metadata: {
      name: "Injury Disruption",
      abbreviation: "INJ",
      categoryId: "modifier_category.availability",
      unit: "0_100",
      description: "Adjustment for disrupted availability due to injuries.",
      tags: ["availability", "risk"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.role_mismatch",
    categoryId: "modifier_category.role",
    entityKinds: ["player", "coach"],
    discoverable: true,
    metadata: {
      name: "Role Mismatch",
      abbreviation: "ROLE",
      categoryId: "modifier_category.role",
      unit: "0_100",
      description: "Adjustment when the sampled role differs from target role.",
      tags: ["role", "contextual"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.data_quality_flag",
    categoryId: "modifier_category.data_quality",
    entityKinds: ["player", "club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Data Quality Flag",
      abbreviation: "DQ",
      categoryId: "modifier_category.data_quality",
      unit: "0_100",
      description: "Adjustment tied to known data quality limitations.",
      tags: ["data_quality", "validation"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.recency_boost",
    categoryId: "modifier_category.temporal",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "Recency Boost",
      abbreviation: "REC+",
      categoryId: "modifier_category.temporal",
      unit: "0_100",
      description: "Adjustment favoring recent performances.",
      tags: ["temporal", "trend"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.consistency",
    categoryId: "modifier_category.performance",
    entityKinds: ["player", "club", "coach", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Consistency",
      abbreviation: "CONS",
      categoryId: "modifier_category.performance",
      unit: "0_100",
      description: "Adjustment based on consistency across time windows.",
      tags: ["performance", "stability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.big_matches",
    categoryId: "modifier_category.performance",
    entityKinds: ["player", "club", "coach", "country"],
    discoverable: true,
    metadata: {
      name: "Big Matches",
      abbreviation: "BIG",
      categoryId: "modifier_category.performance",
      unit: "0_100",
      description: "Adjustment for high-stakes match performance.",
      tags: ["performance", "pressure"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.versatility",
    categoryId: "modifier_category.role",
    entityKinds: ["player", "club", "coach"],
    discoverable: true,
    metadata: {
      name: "Versatility",
      abbreviation: "VERS",
      categoryId: "modifier_category.role",
      unit: "0_100",
      description: "Adjustment for role and tactical versatility.",
      tags: ["role", "adaptability"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.decline_risk",
    categoryId: "modifier_category.temporal",
    entityKinds: ["player", "coach", "club", "country"],
    discoverable: true,
    metadata: {
      name: "Decline Risk",
      abbreviation: "DRISK",
      categoryId: "modifier_category.temporal",
      unit: "0_100",
      description: "Adjustment for signs of downward trend risk.",
      tags: ["temporal", "risk"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.momentum_boost",
    categoryId: "modifier_category.temporal",
    entityKinds: ["player", "coach", "club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Momentum Boost",
      abbreviation: "MOM+",
      categoryId: "modifier_category.temporal",
      unit: "0_100",
      description: "Adjustment for sustained positive trend.",
      tags: ["temporal", "trend"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
  {
    id: "modifier.debt_pressure",
    categoryId: "modifier_category.data_quality",
    entityKinds: ["club", "competition", "country"],
    discoverable: true,
    metadata: {
      name: "Debt Pressure",
      abbreviation: "DEBT",
      categoryId: "modifier_category.data_quality",
      unit: "0_100",
      description: "Adjustment reflecting financial pressure and debt constraints.",
      tags: ["finance", "risk"],
      discoverable: true,
      source: "score-engine.catalog.v1",
    },
  },
];

export function getModifierById(id: ModifierDefinition["id"]): ModifierDefinition | undefined {
  return defaultModifiers.find((modifier) => modifier.id === id);
}

export function listModifiersByCategory(
  categoryId: ModifierDefinition["categoryId"],
): ModifierDefinition[] {
  return defaultModifiers.filter((modifier) => modifier.categoryId === categoryId);
}
