import type { ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

function coachScore(args: {
  id: ScoreDefinition["id"];
  name: string;
  categoryId: ScoreDefinition["categoryId"];
  description: string;
  metrics: ReturnType<typeof mr>[];
  contexts: ReturnType<typeof cr>[];
  modifiers: ReturnType<typeof mor>[];
}): ScoreDefinition {
  return {
    id: args.id,
    name: args.name,
    entityKind: "coach",
    categoryId: args.categoryId,
    description: args.description,
    metricRefs: args.metrics,
    contextRefs: args.contexts,
    modifierRefs: args.modifiers,
    status: "active",
    version: "1.0.0",
    metadata: { source: "score-library.phase-1.4b", discoverable: true },
  };
}

const coreContexts = [
  cr("context.league_strength", 1),
  cr("context.fixture_congestion", 0.9),
  cr("context.squad_stability", 1),
  cr("context.match_importance", 0.8),
  cr("context.competition_reputation", 0.8),
];
const coreModifiers = [
  mor("modifier.consistency", 1),
  mor("modifier.big_matches", 0.9),
  mor("modifier.versatility", 0.8),
  mor("modifier.recency_boost", 0.8),
  mor("modifier.small_sample_size", 0.8),
];

export const coachScoreDefinitions: ScoreDefinition[] = [
  coachScore({
    id: "score.coach_youth_developer",
    name: "Desenvolvedor de Jovens",
    categoryId: "score_category.coach_development",
    description: "Optimizes youth growth and integration.",
    metrics: [
      mr("metric.coach_youth_integration_pct", 1.3),
      mr("metric.academy_output_index", 1.2),
      mr("metric.youth_minutes_pct", 1.1),
      mr("metric.points_per_match", 0.8),
      mr("metric.coach_win_rate", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_elite_manager",
    name: "Gestor de Elite",
    categoryId: "score_category.coach_elite",
    description: "Sustains top-level outcomes under pressure.",
    metrics: [
      mr("metric.coach_win_rate", 1.3),
      mr("metric.coach_trophy_index", 1.2),
      mr("metric.points_per_match", 1.1),
      mr("metric.reputation_index", 1),
      mr("metric.expected_points_per_match", 0.9),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_league_specialist",
    name: "Especialista em Campeonatos",
    categoryId: "score_category.coach_results",
    description: "Consistent league campaign specialist.",
    metrics: [
      mr("metric.championship_win_rate", 1.4),
      mr("metric.points_per_match", 1.2),
      mr("metric.expected_points_per_match", 1),
      mr("metric.coach_win_rate", 0.9),
      mr("metric.title_count_index", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_cup_specialist",
    name: "Especialista em Tacas",
    categoryId: "score_category.coach_results",
    description: "Knockout-format competition expert.",
    metrics: [
      mr("metric.cup_win_rate", 1.4),
      mr("metric.coach_trophy_index", 1.1),
      mr("metric.points_per_match", 1),
      mr("metric.reputation_index", 0.8),
      mr("metric.coach_goal_diff_per90", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_offensive",
    name: "Treinador Ofensivo",
    categoryId: "score_category.coach_style",
    description: "Attack-first coach profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.4),
      mr("metric.xg_per90", 1.2),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.pass_completion_pct", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_defensive",
    name: "Treinador Defensivo",
    categoryId: "score_category.coach_style",
    description: "Defensive structure and control profile.",
    metrics: [
      mr("metric.goals_conceded_per90", 1.4),
      mr("metric.clean_sheets_pct", 1.2),
      mr("metric.duel_win_pct", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_tactical",
    name: "Treinador Tatico",
    categoryId: "score_category.coach_style",
    description: "Tactical adaptation and game-plan profile.",
    metrics: [
      mr("metric.tactical_flexibility_index", 1.4),
      mr("metric.pass_completion_pct", 1.1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.coach_goal_diff_per90", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_motivator",
    name: "Motivador",
    categoryId: "score_category.coach_management",
    description: "Boosts performance in key moments.",
    metrics: [
      mr("metric.coach_win_rate", 1.1),
      mr("metric.points_per_match", 1.1),
      mr("metric.coach_goal_diff_per90", 1),
      mr("metric.cup_win_rate", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: coreContexts,
    modifiers: [mor("modifier.big_matches", 1.2), ...coreModifiers],
  }),
  coachScore({
    id: "score.coach_formador",
    name: "Formador",
    categoryId: "score_category.coach_development",
    description: "Long-term development and progression profile.",
    metrics: [
      mr("metric.academy_output_index", 1.3),
      mr("metric.youth_minutes_pct", 1.2),
      mr("metric.coach_youth_integration_pct", 1.1),
      mr("metric.pass_completion_pct", 0.8),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_rebuilder",
    name: "Reconstrutor",
    categoryId: "score_category.coach_management",
    description: "Rebuilds teams during transition cycles.",
    metrics: [
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.tactical_flexibility_index", 1.1),
      mr("metric.coach_goal_diff_per90", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.reputation_index", 0.7),
    ],
    contexts: [...coreContexts, cr("context.governance_stability", 0.8)],
    modifiers: [...coreModifiers, mor("modifier.momentum_boost", 0.9)],
  }),
  coachScore({
    id: "score.coach_dressing_room_manager",
    name: "Gestor de Balneario",
    categoryId: "score_category.coach_management",
    description: "Maintains squad cohesion and consistency.",
    metrics: [
      mr("metric.coach_win_rate", 1),
      mr("metric.points_per_match", 1),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.expected_points_per_match", 0.9),
      mr("metric.coach_trophy_index", 0.8),
    ],
    contexts: coreContexts,
    modifiers: [mor("modifier.consistency", 1.2), ...coreModifiers],
  }),
  coachScore({
    id: "score.coach_consistent",
    name: "Regular",
    categoryId: "score_category.coach_management",
    description: "Stable baseline performer across seasons.",
    metrics: [
      mr("metric.points_per_match", 1.2),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.coach_win_rate", 1),
      mr("metric.pass_completion_pct", 0.8),
      mr("metric.goals_conceded_per90", 0.8),
    ],
    contexts: coreContexts,
    modifiers: [mor("modifier.consistency", 1.3), ...coreModifiers],
  }),
  coachScore({
    id: "score.coach_innovator",
    name: "Inovador",
    categoryId: "score_category.coach_style",
    description: "High adaptation and model innovation profile.",
    metrics: [
      mr("metric.tactical_flexibility_index", 1.4),
      mr("metric.progressive_passes_per90", 1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.coach_goal_diff_per90", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: coreContexts,
    modifiers: [mor("modifier.versatility", 1.1), ...coreModifiers],
  }),

  coachScore({
    id: "score.coach_pressing_specialist",
    name: "Especialista em Pressao",
    categoryId: "score_category.coach_style",
    description: "High intensity pressing specialist.",
    metrics: [
      mr("metric.pressures_per90", 1.4),
      mr("metric.duel_win_pct", 1.1),
      mr("metric.points_per_match", 1),
      mr("metric.coach_win_rate", 0.9),
      mr("metric.goals_conceded_per90", 0.7),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_possession_specialist",
    name: "Especialista em Posse",
    categoryId: "score_category.coach_style",
    description: "Possession and control specialist.",
    metrics: [
      mr("metric.possession_pct", 1.4),
      mr("metric.pass_completion_pct", 1.3),
      mr("metric.progressive_passes_per90", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_transition_specialist",
    name: "Especialista em Transicao",
    categoryId: "score_category.coach_style",
    description: "Transition game specialist.",
    metrics: [
      mr("metric.goals_scored_per90", 1.2),
      mr("metric.pressures_per90", 1.1),
      mr("metric.xg_per90", 1),
      mr("metric.coach_goal_diff_per90", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_set_piece_specialist",
    name: "Especialista em Bolas Paradas",
    categoryId: "score_category.coach_style",
    description: "Set-piece outcomes specialist.",
    metrics: [
      mr("metric.goals_scored_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.cup_win_rate", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.coach_trophy_index", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_high_risk_attacker",
    name: "Ofensivo de Alto Risco",
    categoryId: "score_category.coach_style",
    description: "High variance attacking profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.4),
      mr("metric.goals_conceded_per90", 0.6),
      mr("metric.xg_per90", 1.2),
      mr("metric.coach_goal_diff_per90", 1),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: coreContexts,
    modifiers: [...coreModifiers, mor("modifier.momentum_boost", 0.9)],
  }),
  coachScore({
    id: "score.coach_low_block_specialist",
    name: "Especialista em Bloco Baixo",
    categoryId: "score_category.coach_style",
    description: "Compact low-block profile.",
    metrics: [
      mr("metric.goals_conceded_per90", 1.4),
      mr("metric.clean_sheets_pct", 1.2),
      mr("metric.duel_win_pct", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.coach_win_rate", 0.8),
    ],
    contexts: coreContexts,
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_project_builder",
    name: "Construtor de Projeto",
    categoryId: "score_category.coach_management",
    description: "Builds sustainable long-term projects.",
    metrics: [
      mr("metric.academy_output_index", 1.1),
      mr("metric.youth_minutes_pct", 1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.tactical_flexibility_index", 1),
      mr("metric.reputation_index", 0.9),
    ],
    contexts: [...coreContexts, cr("context.era_weight", 0.8)],
    modifiers: [...coreModifiers, mor("modifier.momentum_boost", 0.9)],
  }),
  coachScore({
    id: "score.coach_crisis_manager",
    name: "Gestor de Crise",
    categoryId: "score_category.coach_management",
    description: "Stabilizes under difficult conditions.",
    metrics: [
      mr("metric.points_per_match", 1.1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.goals_conceded_per90", 1),
      mr("metric.coach_win_rate", 0.9),
      mr("metric.tactical_flexibility_index", 0.9),
    ],
    contexts: [...coreContexts, cr("context.fixture_difficulty", 0.8)],
    modifiers: [...coreModifiers, mor("modifier.momentum_boost", 1)],
  }),
  coachScore({
    id: "score.coach_club_legend",
    name: "Lenda do Clube",
    categoryId: "score_category.coach_historical",
    description: "Legacy and sustained historical success profile.",
    metrics: [
      mr("metric.title_count_index", 1.4),
      mr("metric.coach_trophy_index", 1.2),
      mr("metric.reputation_index", 1.1),
      mr("metric.championship_win_rate", 0.9),
      mr("metric.cup_win_rate", 0.9),
    ],
    contexts: [...coreContexts, cr("context.era_weight", 0.9)],
    modifiers: coreModifiers,
  }),
  coachScore({
    id: "score.coach_overachiever",
    name: "Sobre-Executante",
    categoryId: "score_category.coach_results",
    description: "Outperforms expected baseline consistently.",
    metrics: [
      mr("metric.expected_points_per_match", 1.3),
      mr("metric.points_per_match", 1.2),
      mr("metric.coach_goal_diff_per90", 1),
      mr("metric.coach_win_rate", 0.9),
      mr("metric.tactical_flexibility_index", 0.8),
    ],
    contexts: coreContexts,
    modifiers: [...coreModifiers, mor("modifier.consistency", 1.1)],
  }),
  coachScore({
    id: "score.coach_underdog_specialist",
    name: "Especialista em Underdogs",
    categoryId: "score_category.coach_results",
    description: "Strong underdog and upset performance profile.",
    metrics: [
      mr("metric.competition_surprise_index", 1.2),
      mr("metric.cup_win_rate", 1),
      mr("metric.points_per_match", 1),
      mr("metric.coach_win_rate", 0.9),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: [...coreContexts, cr("context.opponent_quality", 0.9)],
    modifiers: [...coreModifiers, mor("modifier.big_matches", 1.1)],
  }),
  coachScore({
    id: "score.coach_data_driven",
    name: "Orientado a Dados",
    categoryId: "score_category.coach_style",
    description: "Data-informed decision and optimization profile.",
    metrics: [
      mr("metric.expected_points_per_match", 1.3),
      mr("metric.tactical_flexibility_index", 1.1),
      mr("metric.pass_completion_pct", 1),
      mr("metric.progressive_passes_per90", 0.9),
      mr("metric.coach_goal_diff_per90", 0.8),
    ],
    contexts: coreContexts,
    modifiers: [mor("modifier.data_quality_flag", 1), ...coreModifiers],
  }),
];
