import type { AttributeId, ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const ar = (attributeId: AttributeId, weight: number) => ({ attributeId, weight });
const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

export const defenderScores: ScoreDefinition[] = [
  {
    id: "score.central_defender",
    name: "Central Defender",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.positioning", 1.3),
      ar("attribute.decisions", 1.2),
      ar("attribute.stamina", 0.9),
      ar("attribute.pace", 0.8),
      ar("attribute.first_touch", 0.7),
    ],
    metricRefs: [
      mr("metric.duel_win_pct", 1.3),
      mr("metric.clean_sheets_pct", 1.1),
      mr("metric.pass_completion_pct", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.8),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.2),
      mor("modifier.consistency", 1),
      mor("modifier.big_matches", 0.8),
    ],
    status: "active",
  },
  {
    id: "score.ball_playing_defender",
    name: "Ball Playing Defender",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.passing", 1.3),
      ar("attribute.first_touch", 1.1),
      ar("attribute.vision", 1),
      ar("attribute.decisions", 1),
      ar("attribute.positioning", 0.8),
    ],
    metricRefs: [
      mr("metric.pass_completion_pct", 1.3),
      mr("metric.key_passes_per90", 1),
      mr("metric.xa_per90", 0.9),
      mr("metric.duel_win_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.8),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.2),
      mor("modifier.versatility", 1),
      mor("modifier.consistency", 0.8),
    ],
    status: "active",
  },
  {
    id: "score.no_nonsense_centre_back",
    name: "No-Nonsense Centre Back",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.positioning", 1.3),
      ar("attribute.decisions", 1.1),
      ar("attribute.stamina", 1),
      ar("attribute.pace", 0.8),
      ar("attribute.command_of_area", 0.6),
    ],
    metricRefs: [
      mr("metric.duel_win_pct", 1.4),
      mr("metric.clean_sheets_pct", 1.1),
      mr("metric.pass_completion_pct", 0.8),
      mr("metric.points_per_match", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1.1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.7),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.2),
      mor("modifier.big_matches", 1),
      mor("modifier.consistency", 0.8),
    ],
    status: "active",
  },
  {
    id: "score.libero",
    name: "Libero",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.passing", 1.2),
      ar("attribute.vision", 1.2),
      ar("attribute.decisions", 1.1),
      ar("attribute.first_touch", 1),
      ar("attribute.positioning", 0.8),
    ],
    metricRefs: [
      mr("metric.pass_completion_pct", 1.2),
      mr("metric.key_passes_per90", 1),
      mr("metric.xa_per90", 0.9),
      mr("metric.duel_win_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.9),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.2),
      mor("modifier.versatility", 1.1),
      mor("modifier.consistency", 0.8),
    ],
    status: "active",
  },
  {
    id: "score.full_back",
    name: "Full Back",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.stamina", 1.3),
      ar("attribute.pace", 1.1),
      ar("attribute.passing", 0.9),
      ar("attribute.positioning", 0.9),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.duel_win_pct", 1.1),
      mr("metric.pass_completion_pct", 1),
      mr("metric.assists_per90", 0.9),
      mr("metric.key_passes_per90", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.8),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.consistency", 1),
      mor("modifier.versatility", 0.9),
    ],
    status: "active",
  },
  {
    id: "score.wing_back",
    name: "Wing Back",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.stamina", 1.4),
      ar("attribute.acceleration", 1.1),
      ar("attribute.pace", 1.1),
      ar("attribute.passing", 0.9),
      ar("attribute.first_touch", 0.8),
    ],
    metricRefs: [
      mr("metric.assists_per90", 1.1),
      mr("metric.key_passes_per90", 1),
      mr("metric.xa_per90", 1),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.8),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.versatility", 1),
      mor("modifier.consistency", 0.9),
    ],
    status: "active",
  },
  {
    id: "score.complete_wing_back",
    name: "Complete Wing Back",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.stamina", 1.3),
      ar("attribute.acceleration", 1.1),
      ar("attribute.pace", 1.1),
      ar("attribute.vision", 1),
      ar("attribute.first_touch", 0.9),
    ],
    metricRefs: [
      mr("metric.assists_per90", 1.2),
      mr("metric.key_passes_per90", 1.1),
      mr("metric.xa_per90", 1),
      mr("metric.duel_win_pct", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.8),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.versatility", 1.1),
      mor("modifier.consistency", 0.9),
    ],
    status: "active",
  },
  {
    id: "score.inverted_wing_back",
    name: "Inverted Wing Back",
    entityKind: "player",
    categoryId: "score_category.player_defender",
    attributeRefs: [
      ar("attribute.passing", 1.2),
      ar("attribute.first_touch", 1.1),
      ar("attribute.vision", 1),
      ar("attribute.decisions", 1),
      ar("attribute.positioning", 0.9),
    ],
    metricRefs: [
      mr("metric.pass_completion_pct", 1.2),
      mr("metric.key_passes_per90", 1),
      mr("metric.xa_per90", 0.9),
      mr("metric.duel_win_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: [
      cr("context.league_strength", 1),
      cr("context.minutes", 1),
      cr("context.team_strength", 0.9),
    ],
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.versatility", 1),
      mor("modifier.consistency", 0.9),
    ],
    status: "active",
  },
];
