import type { AttributeId, ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const ar = (attributeId: AttributeId, weight: number) => ({ attributeId, weight });
const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

const sharedContextRefs = [
  cr("context.age", 0.8),
  cr("context.minutes", 1),
  cr("context.league_strength", 1),
  cr("context.competition_reputation", 0.9),
  cr("context.team_strength", 0.8),
];
const sharedModifierRefs = [
  mor("modifier.low_minutes", 1.2),
  mor("modifier.consistency", 1),
  mor("modifier.big_matches", 0.9),
  mor("modifier.versatility", 0.8),
];

export const forwardScores: ScoreDefinition[] = [
  {
    id: "score.winger",
    name: "Winger",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.acceleration", 1.3),
      ar("attribute.pace", 1.2),
      ar("attribute.first_touch", 1),
      ar("attribute.passing", 0.9),
      ar("attribute.vision", 0.8),
    ],
    metricRefs: [
      mr("metric.assists_per90", 1.2),
      mr("metric.key_passes_per90", 1.1),
      mr("metric.xa_per90", 1),
      mr("metric.goals_per90", 0.7),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.inverted_winger",
    name: "Inverted Winger",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.acceleration", 1.2),
      ar("attribute.pace", 1.1),
      ar("attribute.finishing", 1),
      ar("attribute.first_touch", 1),
      ar("attribute.vision", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.1),
      mr("metric.assists_per90", 1),
      mr("metric.xg_per90", 1),
      mr("metric.key_passes_per90", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.inside_forward",
    name: "Inside Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.3),
      ar("attribute.acceleration", 1.1),
      ar("attribute.pace", 1.1),
      ar("attribute.first_touch", 1),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.3),
      mr("metric.xg_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.assists_per90", 0.7),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.wide_playmaker",
    name: "Wide Playmaker",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.vision", 1.3),
      ar("attribute.passing", 1.2),
      ar("attribute.first_touch", 1.1),
      ar("attribute.decisions", 0.9),
      ar("attribute.acceleration", 0.8),
    ],
    metricRefs: [
      mr("metric.key_passes_per90", 1.3),
      mr("metric.xa_per90", 1.1),
      mr("metric.assists_per90", 1),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.raumdeuter",
    name: "Raumdeuter",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.2),
      ar("attribute.acceleration", 1.1),
      ar("attribute.pace", 1),
      ar("attribute.positioning", 1),
      ar("attribute.decisions", 0.9),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.2),
      mr("metric.xg_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.advanced_forward",
    name: "Advanced Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.4),
      ar("attribute.acceleration", 1.2),
      ar("attribute.pace", 1.2),
      ar("attribute.first_touch", 1),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.4),
      mr("metric.xg_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.assists_per90", 0.6),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.deep_lying_forward",
    name: "Deep Lying Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.first_touch", 1.2),
      ar("attribute.passing", 1.1),
      ar("attribute.vision", 1.1),
      ar("attribute.finishing", 1),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.assists_per90", 1.1),
      mr("metric.key_passes_per90", 1.1),
      mr("metric.goals_per90", 1),
      mr("metric.xa_per90", 1),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.complete_forward",
    name: "Complete Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.2),
      ar("attribute.first_touch", 1.1),
      ar("attribute.passing", 1),
      ar("attribute.acceleration", 1),
      ar("attribute.stamina", 0.9),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.2),
      mr("metric.assists_per90", 1),
      mr("metric.xg_per90", 1),
      mr("metric.key_passes_per90", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.target_forward",
    name: "Target Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.first_touch", 1.1),
      ar("attribute.finishing", 1.1),
      ar("attribute.stamina", 1),
      ar("attribute.decisions", 0.9),
      ar("attribute.passing", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.2),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.assists_per90", 0.8),
      mr("metric.duel_win_pct", 1),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.pressing_forward",
    name: "Pressing Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.stamina", 1.3),
      ar("attribute.acceleration", 1.1),
      ar("attribute.pace", 1),
      ar("attribute.decisions", 0.9),
      ar("attribute.finishing", 0.9),
    ],
    metricRefs: [
      mr("metric.pressures_per90", 1.3),
      mr("metric.goals_per90", 1),
      mr("metric.xg_per90", 0.9),
      mr("metric.points_per_match", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.false_nine",
    name: "False Nine",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.first_touch", 1.2),
      ar("attribute.vision", 1.2),
      ar("attribute.passing", 1.1),
      ar("attribute.decisions", 1),
      ar("attribute.finishing", 0.8),
    ],
    metricRefs: [
      mr("metric.assists_per90", 1.2),
      mr("metric.key_passes_per90", 1.2),
      mr("metric.goals_per90", 0.9),
      mr("metric.xa_per90", 1),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.poacher",
    name: "Poacher",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.5),
      ar("attribute.acceleration", 1.2),
      ar("attribute.pace", 1.1),
      ar("attribute.first_touch", 1),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.5),
      mr("metric.xg_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.points_per_match", 0.7),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.trequartista",
    name: "Trequartista",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.vision", 1.3),
      ar("attribute.first_touch", 1.2),
      ar("attribute.passing", 1.1),
      ar("attribute.finishing", 0.9),
      ar("attribute.decisions", 0.9),
    ],
    metricRefs: [
      mr("metric.key_passes_per90", 1.3),
      mr("metric.assists_per90", 1.1),
      mr("metric.xa_per90", 1.1),
      mr("metric.goals_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
];
