import type { AttributeId, ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const ar = (attributeId: AttributeId, weight: number) => ({ attributeId, weight });
const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

const sharedContextRefs = [
  cr("context.minutes", 1),
  cr("context.league_strength", 1),
  cr("context.team_strength", 0.8),
];
const sharedModifierRefs = [
  mor("modifier.low_minutes", 1.1),
  mor("modifier.consistency", 1),
  mor("modifier.versatility", 0.8),
];

export const midfielderScores: ScoreDefinition[] = [
  {
    id: "score.defensive_midfielder",
    name: "Defensive Midfielder",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.positioning", 1.3),
      ar("attribute.decisions", 1.2),
      ar("attribute.stamina", 1),
      ar("attribute.passing", 0.9),
      ar("attribute.vision", 0.8),
    ],
    metricRefs: [
      mr("metric.duel_win_pct", 1.2),
      mr("metric.pass_completion_pct", 1.1),
      mr("metric.points_per_match", 0.8),
      mr("metric.clean_sheets_pct", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.anchor",
    name: "Anchor",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.positioning", 1.4),
      ar("attribute.decisions", 1.2),
      ar("attribute.stamina", 1),
      ar("attribute.passing", 0.8),
      ar("attribute.first_touch", 0.7),
    ],
    metricRefs: [
      mr("metric.duel_win_pct", 1.3),
      mr("metric.clean_sheets_pct", 1),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.points_per_match", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.half_back",
    name: "Half Back",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.positioning", 1.2),
      ar("attribute.passing", 1.1),
      ar("attribute.decisions", 1.1),
      ar("attribute.first_touch", 0.9),
      ar("attribute.vision", 0.8),
    ],
    metricRefs: [
      mr("metric.pass_completion_pct", 1.2),
      mr("metric.duel_win_pct", 1.1),
      mr("metric.key_passes_per90", 0.8),
      mr("metric.clean_sheets_pct", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.deep_lying_playmaker",
    name: "Deep Lying Playmaker",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.passing", 1.3),
      ar("attribute.vision", 1.3),
      ar("attribute.decisions", 1.1),
      ar("attribute.first_touch", 1),
      ar("attribute.positioning", 0.7),
    ],
    metricRefs: [
      mr("metric.pass_completion_pct", 1.3),
      mr("metric.key_passes_per90", 1.1),
      mr("metric.xa_per90", 1),
      mr("metric.assists_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.regista",
    name: "Regista",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.passing", 1.3),
      ar("attribute.vision", 1.3),
      ar("attribute.first_touch", 1),
      ar("attribute.decisions", 1),
      ar("attribute.stamina", 0.8),
    ],
    metricRefs: [
      mr("metric.key_passes_per90", 1.2),
      mr("metric.xa_per90", 1.1),
      mr("metric.pass_completion_pct", 1),
      mr("metric.assists_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.consistency", 1),
      mor("modifier.versatility", 1),
    ],
    status: "active",
  },
  {
    id: "score.roaming_playmaker",
    name: "Roaming Playmaker",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.vision", 1.2),
      ar("attribute.passing", 1.1),
      ar("attribute.stamina", 1.1),
      ar("attribute.acceleration", 0.9),
      ar("attribute.decisions", 0.9),
    ],
    metricRefs: [
      mr("metric.key_passes_per90", 1.1),
      mr("metric.xa_per90", 1),
      mr("metric.assists_per90", 0.9),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.versatility", 1.1),
      mor("modifier.consistency", 0.9),
    ],
    status: "active",
  },
  {
    id: "score.ball_winning_midfielder",
    name: "Ball Winning Midfielder",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.stamina", 1.3),
      ar("attribute.positioning", 1.1),
      ar("attribute.decisions", 1),
      ar("attribute.pace", 0.9),
      ar("attribute.passing", 0.7),
    ],
    metricRefs: [
      mr("metric.duel_win_pct", 1.3),
      mr("metric.clean_sheets_pct", 0.9),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.points_per_match", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.box_to_box_midfielder",
    name: "Box to Box Midfielder",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.stamina", 1.4),
      ar("attribute.acceleration", 1),
      ar("attribute.decisions", 1),
      ar("attribute.passing", 0.9),
      ar("attribute.finishing", 0.7),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1),
      mr("metric.assists_per90", 1),
      mr("metric.duel_win_pct", 1),
      mr("metric.key_passes_per90", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.versatility", 1.1),
      mor("modifier.consistency", 0.9),
    ],
    status: "active",
  },
  {
    id: "score.carrilero",
    name: "Carrilero",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.stamina", 1.3),
      ar("attribute.passing", 1),
      ar("attribute.positioning", 1),
      ar("attribute.decisions", 0.9),
      ar("attribute.pace", 0.8),
    ],
    metricRefs: [
      mr("metric.pass_completion_pct", 1.1),
      mr("metric.duel_win_pct", 1),
      mr("metric.key_passes_per90", 0.8),
      mr("metric.assists_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.central_midfielder",
    name: "Central Midfielder",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.passing", 1.1),
      ar("attribute.decisions", 1.1),
      ar("attribute.first_touch", 1),
      ar("attribute.stamina", 0.9),
      ar("attribute.vision", 0.9),
    ],
    metricRefs: [
      mr("metric.pass_completion_pct", 1.2),
      mr("metric.key_passes_per90", 0.9),
      mr("metric.duel_win_pct", 0.9),
      mr("metric.assists_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: sharedModifierRefs,
    status: "active",
  },
  {
    id: "score.mezzala",
    name: "Mezzala",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.passing", 1.1),
      ar("attribute.vision", 1.1),
      ar("attribute.first_touch", 1),
      ar("attribute.acceleration", 1),
      ar("attribute.finishing", 0.8),
    ],
    metricRefs: [
      mr("metric.assists_per90", 1.1),
      mr("metric.key_passes_per90", 1.1),
      mr("metric.goals_per90", 0.9),
      mr("metric.xa_per90", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.versatility", 1.1),
      mor("modifier.consistency", 0.9),
    ],
    status: "active",
  },
  {
    id: "score.advanced_playmaker",
    name: "Advanced Playmaker",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.vision", 1.3),
      ar("attribute.passing", 1.2),
      ar("attribute.first_touch", 1.1),
      ar("attribute.decisions", 1),
      ar("attribute.finishing", 0.7),
    ],
    metricRefs: [
      mr("metric.key_passes_per90", 1.3),
      mr("metric.xa_per90", 1.2),
      mr("metric.assists_per90", 1),
      mr("metric.pass_completion_pct", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.consistency", 1),
      mor("modifier.big_matches", 0.9),
    ],
    status: "active",
  },
  {
    id: "score.enganche",
    name: "Enganche",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.vision", 1.3),
      ar("attribute.passing", 1.2),
      ar("attribute.first_touch", 1.1),
      ar("attribute.decisions", 1),
      ar("attribute.acceleration", 0.6),
    ],
    metricRefs: [
      mr("metric.key_passes_per90", 1.3),
      mr("metric.xa_per90", 1.2),
      mr("metric.assists_per90", 0.9),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContextRefs,
    modifierRefs: [
      mor("modifier.low_minutes", 1.1),
      mor("modifier.consistency", 1),
      mor("modifier.big_matches", 0.9),
    ],
    status: "active",
  },
];
