import type { AttributeId, ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const ar = (attributeId: AttributeId, weight: number) => ({ attributeId, weight });
const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

const sharedContexts = [
  cr("context.age", 0.8),
  cr("context.minutes", 1),
  cr("context.league_strength", 1),
  cr("context.competition_reputation", 0.9),
  cr("context.team_strength", 0.8),
];
const sharedModifiers = [
  mor("modifier.low_minutes", 1.2),
  mor("modifier.consistency", 1),
  mor("modifier.big_matches", 0.9),
  mor("modifier.versatility", 0.8),
];

export const specialistPlayerScores: ScoreDefinition[] = [
  {
    id: "score.shadow_striker",
    name: "Shadow Striker",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.finishing", 1.3),
      ar("attribute.acceleration", 1.1),
      ar("attribute.first_touch", 1),
      ar("attribute.vision", 0.9),
      ar("attribute.decisions", 0.9),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.3),
      mr("metric.xg_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.key_passes_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.second_striker",
    name: "Second Striker",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.2),
      ar("attribute.first_touch", 1.1),
      ar("attribute.vision", 1),
      ar("attribute.acceleration", 1),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.2),
      mr("metric.assists_per90", 1),
      mr("metric.xg_per90", 1),
      mr("metric.key_passes_per90", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.channel_runner",
    name: "Channel Runner",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.acceleration", 1.3),
      ar("attribute.pace", 1.2),
      ar("attribute.finishing", 1),
      ar("attribute.first_touch", 0.9),
      ar("attribute.stamina", 0.9),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.1),
      mr("metric.xg_per90", 1),
      mr("metric.shots_on_target_pct", 0.9),
      mr("metric.pressures_per90", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.wide_target_forward",
    name: "Wide Target Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.first_touch", 1.1),
      ar("attribute.finishing", 1.1),
      ar("attribute.stamina", 1),
      ar("attribute.passing", 0.9),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.1),
      mr("metric.assists_per90", 0.9),
      mr("metric.duel_win_pct", 1),
      mr("metric.shots_on_target_pct", 0.9),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.pressing_winger",
    name: "Pressing Winger",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.stamina", 1.3),
      ar("attribute.acceleration", 1.1),
      ar("attribute.pace", 1),
      ar("attribute.first_touch", 0.9),
      ar("attribute.decisions", 0.8),
    ],
    metricRefs: [
      mr("metric.pressures_per90", 1.4),
      mr("metric.assists_per90", 0.9),
      mr("metric.goals_per90", 0.8),
      mr("metric.key_passes_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.clinical_finisher",
    name: "Clinical Finisher",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.5),
      ar("attribute.first_touch", 1.1),
      ar("attribute.decisions", 0.9),
      ar("attribute.acceleration", 0.9),
      ar("attribute.pace", 0.8),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.5),
      mr("metric.shots_on_target_pct", 1.2),
      mr("metric.xg_per90", 1),
      mr("metric.points_per_match", 0.7),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.complete_wide_forward",
    name: "Complete Wide Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.finishing", 1.1),
      ar("attribute.first_touch", 1.1),
      ar("attribute.acceleration", 1.1),
      ar("attribute.passing", 1),
      ar("attribute.vision", 0.9),
    ],
    metricRefs: [
      mr("metric.goals_per90", 1.1),
      mr("metric.assists_per90", 1.1),
      mr("metric.key_passes_per90", 1),
      mr("metric.xa_per90", 1),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.advanced_creator",
    name: "Advanced Creator",
    entityKind: "player",
    categoryId: "score_category.player_midfielder",
    attributeRefs: [
      ar("attribute.vision", 1.4),
      ar("attribute.passing", 1.2),
      ar("attribute.first_touch", 1.1),
      ar("attribute.decisions", 1),
      ar("attribute.acceleration", 0.7),
    ],
    metricRefs: [
      mr("metric.key_passes_per90", 1.4),
      mr("metric.xa_per90", 1.2),
      mr("metric.assists_per90", 1),
      mr("metric.pass_completion_pct", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
  {
    id: "score.defensive_forward",
    name: "Defensive Forward",
    entityKind: "player",
    categoryId: "score_category.player_forward",
    attributeRefs: [
      ar("attribute.stamina", 1.3),
      ar("attribute.acceleration", 1),
      ar("attribute.decisions", 1),
      ar("attribute.finishing", 0.8),
      ar("attribute.first_touch", 0.8),
    ],
    metricRefs: [
      mr("metric.pressures_per90", 1.4),
      mr("metric.duel_win_pct", 1),
      mr("metric.goals_per90", 0.8),
      mr("metric.assists_per90", 0.8),
      mr("metric.minutes_played", 0.8),
    ],
    contextRefs: sharedContexts,
    modifierRefs: sharedModifiers,
    status: "active",
  },
];
