import type { ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

function competitionScore(args: {
  id: ScoreDefinition["id"];
  name: string;
  categoryId: ScoreDefinition["categoryId"];
  description: string;
  metrics: ReturnType<typeof mr>[];
  contexts: ReturnType<typeof cr>[];
  modifiers: ReturnType<typeof mor>[];
}): ScoreDefinition {
  return {
    id: args.id,
    name: args.name,
    entityKind: "competition",
    categoryId: args.categoryId,
    description: args.description,
    metricRefs: args.metrics,
    contextRefs: args.contexts,
    modifierRefs: args.modifiers,
    status: "active",
    version: "1.0.0",
    metadata: { source: "score-library.phase-1.4b", discoverable: true },
  };
}

const compContexts = [
  cr("context.competition_reputation", 1),
  cr("context.continental_strength", 1),
  cr("context.economic_context", 0.9),
  cr("context.governance_stability", 0.8),
  cr("context.era_weight", 0.8),
];
const compModifiers = [
  mor("modifier.consistency", 1),
  mor("modifier.momentum_boost", 0.9),
  mor("modifier.data_quality_flag", 0.8),
  mor("modifier.small_sample_size", 0.8),
  mor("modifier.debt_pressure", 0.7),
];

export const competitionScoreDefinitions: ScoreDefinition[] = [
  competitionScore({
    id: "score.competition_physical",
    name: "Competicao Fisica",
    categoryId: "score_category.competition_style",
    description: "High duel and physical contest profile.",
    metrics: [
      mr("metric.duel_win_pct", 1.3),
      mr("metric.pressures_per90", 1.2),
      mr("metric.goals_conceded_per90", 0.9),
      mr("metric.points_per_match", 0.8),
      mr("metric.competition_balance_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_technical",
    name: "Competicao Tecnica",
    categoryId: "score_category.competition_style",
    description: "Technical quality and control profile.",
    metrics: [
      mr("metric.pass_completion_pct", 1.3),
      mr("metric.progressive_passes_per90", 1.1),
      mr("metric.xa_per90", 1),
      mr("metric.possession_pct", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_tactical",
    name: "Competicao Tatica",
    categoryId: "score_category.competition_style",
    description: "Tactical sophistication profile.",
    metrics: [
      mr("metric.tactical_flexibility_index", 1.3),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.pass_completion_pct", 1),
      mr("metric.competition_balance_index", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_offensive",
    name: "Competicao Ofensiva",
    categoryId: "score_category.competition_style",
    description: "Goal-rich attacking profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.4),
      mr("metric.xg_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.competition_surprise_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_defensive",
    name: "Competicao Defensiva",
    categoryId: "score_category.competition_style",
    description: "Defensive structure and low concession profile.",
    metrics: [
      mr("metric.goals_conceded_per90", 1.4),
      mr("metric.clean_sheets_pct", 1.2),
      mr("metric.duel_win_pct", 0.9),
      mr("metric.points_per_match", 0.8),
      mr("metric.competition_balance_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_balanced",
    name: "Competicao Equilibrada",
    categoryId: "score_category.competition_style",
    description: "Balanced attacking and defensive profile.",
    metrics: [
      mr("metric.competition_balance_index", 1.4),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.goals_scored_per90", 0.9),
      mr("metric.goals_conceded_per90", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_competitive",
    name: "Competicao Competitiva",
    categoryId: "score_category.competition_results",
    description: "High competitiveness profile.",
    metrics: [
      mr("metric.competition_balance_index", 1.3),
      mr("metric.competition_surprise_index", 1.2),
      mr("metric.expected_points_per_match", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_historic",
    name: "Competicao Historica",
    categoryId: "score_category.competition_historical",
    description: "Long legacy and historic significance profile.",
    metrics: [
      mr("metric.title_count_index", 1.4),
      mr("metric.reputation_index", 1.3),
      mr("metric.continental_points", 1),
      mr("metric.financial_strength_index", 0.8),
      mr("metric.expected_points_per_match", 0.7),
    ],
    contexts: [...compContexts, cr("context.era_weight", 1)],
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_emerging",
    name: "Competicao Emergente",
    categoryId: "score_category.competition_growth",
    description: "Rising competition profile.",
    metrics: [
      mr("metric.competition_surprise_index", 1.2),
      mr("metric.reputation_index", 1),
      mr("metric.financial_strength_index", 0.9),
      mr("metric.expected_points_per_match", 0.9),
      mr("metric.youth_minutes_pct", 0.8),
    ],
    contexts: compContexts,
    modifiers: [...compModifiers, mor("modifier.momentum_boost", 1)],
  }),
  competitionScore({
    id: "score.competition_elite",
    name: "Competicao de Elite",
    categoryId: "score_category.competition_results",
    description: "Top-tier quality and output profile.",
    metrics: [
      mr("metric.reputation_index", 1.4),
      mr("metric.continental_points", 1.2),
      mr("metric.financial_strength_index", 1),
      mr("metric.expected_points_per_match", 0.9),
      mr("metric.title_count_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_developer",
    name: "Competicao Formadora",
    categoryId: "score_category.competition_growth",
    description: "Strong player development ecosystem profile.",
    metrics: [
      mr("metric.academy_output_index", 1.3),
      mr("metric.youth_minutes_pct", 1.2),
      mr("metric.country_talent_depth_index", 1),
      mr("metric.reputation_index", 0.8),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: [...compContexts, cr("context.talent_pool_depth", 1)],
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_development",
    name: "Competicao de Desenvolvimento",
    categoryId: "score_category.competition_growth",
    description: "Development pathway competition profile.",
    metrics: [
      mr("metric.youth_minutes_pct", 1.3),
      mr("metric.academy_output_index", 1.1),
      mr("metric.competition_surprise_index", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: [...compContexts, cr("context.talent_pool_depth", 0.9)],
    modifiers: compModifiers,
  }),

  competitionScore({
    id: "score.competition_high_scoring",
    name: "Competicao de Muitos Golos",
    categoryId: "score_category.competition_style",
    description: "High-scoring game profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.4),
      mr("metric.shots_on_target_pct", 1.1),
      mr("metric.xg_per90", 1),
      mr("metric.goals_conceded_per90", 0.7),
      mr("metric.competition_surprise_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_low_scoring",
    name: "Competicao de Poucos Golos",
    categoryId: "score_category.competition_style",
    description: "Low-scoring controlled profile.",
    metrics: [
      mr("metric.goals_conceded_per90", 1.2),
      mr("metric.clean_sheets_pct", 1.1),
      mr("metric.goals_scored_per90", 0.7),
      mr("metric.competition_balance_index", 0.9),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_possession",
    name: "Competicao de Posse",
    categoryId: "score_category.competition_style",
    description: "Possession-heavy profile.",
    metrics: [
      mr("metric.possession_pct", 1.4),
      mr("metric.pass_completion_pct", 1.2),
      mr("metric.progressive_passes_per90", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_direct",
    name: "Competicao Direta",
    categoryId: "score_category.competition_style",
    description: "Direct and transition-heavy profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.2),
      mr("metric.pressures_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.pass_completion_pct", 0.7),
      mr("metric.competition_surprise_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_stable",
    name: "Competicao Estavel",
    categoryId: "score_category.competition_management",
    description: "Stable and predictable competition profile.",
    metrics: [
      mr("metric.competition_balance_index", 1.1),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.reputation_index", 1),
      mr("metric.financial_strength_index", 0.9),
      mr("metric.title_count_index", 0.8),
    ],
    contexts: [...compContexts, cr("context.governance_stability", 1)],
    modifiers: [mor("modifier.consistency", 1.2), ...compModifiers],
  }),
  competitionScore({
    id: "score.competition_unstable",
    name: "Competicao Instavel",
    categoryId: "score_category.competition_management",
    description: "Volatile and unstable competition profile.",
    metrics: [
      mr("metric.competition_surprise_index", 1.3),
      mr("metric.competition_balance_index", 1),
      mr("metric.expected_points_per_match", 0.8),
      mr("metric.reputation_index", 0.8),
      mr("metric.financial_strength_index", 0.7),
    ],
    contexts: [...compContexts, cr("context.governance_stability", 1)],
    modifiers: [mor("modifier.debt_pressure", 1), ...compModifiers],
  }),
  competitionScore({
    id: "score.competition_financial_power",
    name: "Competicao Financeiramente Forte",
    categoryId: "score_category.competition_finance",
    description: "High financial capacity ecosystem profile.",
    metrics: [
      mr("metric.financial_strength_index", 1.4),
      mr("metric.reputation_index", 1.2),
      mr("metric.continental_points", 1),
      mr("metric.expected_points_per_match", 0.8),
      mr("metric.title_count_index", 0.8),
    ],
    contexts: [...compContexts, cr("context.economic_context", 1)],
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_talent_hub",
    name: "Competicao Hub de Talento",
    categoryId: "score_category.competition_growth",
    description: "Talent generation and circulation hub.",
    metrics: [
      mr("metric.academy_output_index", 1.2),
      mr("metric.country_talent_depth_index", 1.1),
      mr("metric.youth_minutes_pct", 1),
      mr("metric.player_sales_per_season", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: [...compContexts, cr("context.talent_pool_depth", 1)],
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_global_showcase",
    name: "Competicao Montra Global",
    categoryId: "score_category.competition_historical",
    description: "Global attention and showcase profile.",
    metrics: [
      mr("metric.reputation_index", 1.4),
      mr("metric.continental_points", 1.2),
      mr("metric.financial_strength_index", 1),
      mr("metric.title_count_index", 0.9),
      mr("metric.expected_points_per_match", 0.7),
    ],
    contexts: [...compContexts, cr("context.continental_strength", 1)],
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_underdog_friendly",
    name: "Competicao Favoravel a Underdogs",
    categoryId: "score_category.competition_results",
    description: "Environment with high underdog viability.",
    metrics: [
      mr("metric.competition_surprise_index", 1.4),
      mr("metric.competition_balance_index", 1.1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: [...compModifiers, mor("modifier.big_matches", 0.9)],
  }),
  competitionScore({
    id: "score.competition_title_concentrated",
    name: "Competicao Concentrada em Titulos",
    categoryId: "score_category.competition_historical",
    description: "Title concentration among few dominant teams.",
    metrics: [
      mr("metric.title_count_index", 1.3),
      mr("metric.competition_balance_index", 0.8),
      mr("metric.reputation_index", 1),
      mr("metric.financial_strength_index", 0.9),
      mr("metric.continental_points", 0.9),
    ],
    contexts: compContexts,
    modifiers: compModifiers,
  }),
  competitionScore({
    id: "score.competition_modernized",
    name: "Competicao Modernizada",
    categoryId: "score_category.competition_growth",
    description: "Modern tactical and operational evolution profile.",
    metrics: [
      mr("metric.tactical_flexibility_index", 1.2),
      mr("metric.progressive_passes_per90", 1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.reputation_index", 0.9),
      mr("metric.financial_strength_index", 0.8),
    ],
    contexts: compContexts,
    modifiers: [...compModifiers, mor("modifier.momentum_boost", 0.9)],
  }),
];
