import type { ContextId, MetricId, ModifierId, ScoreDefinition } from "../../types";

const mr = (metricId: MetricId, weight: number) => ({ metricId, weight });
const cr = (contextId: ContextId, weight: number) => ({ contextId, weight });
const mor = (modifierId: ModifierId, weight: number) => ({ modifierId, weight });

function countryScore(args: {
  id: ScoreDefinition["id"];
  name: string;
  categoryId: ScoreDefinition["categoryId"];
  description: string;
  metrics: ReturnType<typeof mr>[];
  contexts: ReturnType<typeof cr>[];
  modifiers: ReturnType<typeof mor>[];
}): ScoreDefinition {
  return {
    id: args.id,
    name: args.name,
    entityKind: "country",
    categoryId: args.categoryId,
    description: args.description,
    metricRefs: args.metrics,
    contextRefs: args.contexts,
    modifierRefs: args.modifiers,
    status: "active",
    version: "1.0.0",
    metadata: { source: "score-library.phase-1.4b", discoverable: true },
  };
}

const countryContexts = [
  cr("context.continental_strength", 1),
  cr("context.competition_reputation", 0.9),
  cr("context.economic_context", 0.8),
  cr("context.talent_pool_depth", 1),
  cr("context.era_weight", 0.8),
];
const countryModifiers = [
  mor("modifier.consistency", 1),
  mor("modifier.big_matches", 0.9),
  mor("modifier.momentum_boost", 0.8),
  mor("modifier.decline_risk", 0.8),
  mor("modifier.data_quality_flag", 0.8),
];

export const countryScoreDefinitions: ScoreDefinition[] = [
  countryScore({
    id: "score.country_world_power",
    name: "Potencia Mundial",
    categoryId: "score_category.country_power",
    description: "Global top-tier national profile.",
    metrics: [
      mr("metric.reputation_index", 1.4),
      mr("metric.title_count_index", 1.3),
      mr("metric.continental_points", 1.1),
      mr("metric.country_talent_depth_index", 1),
      mr("metric.financial_strength_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_continental_power",
    name: "Potencia Continental",
    categoryId: "score_category.country_power",
    description: "Strong continental influence profile.",
    metrics: [
      mr("metric.continental_points", 1.4),
      mr("metric.reputation_index", 1.2),
      mr("metric.country_talent_depth_index", 1),
      mr("metric.title_count_index", 0.8),
      mr("metric.financial_strength_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_talent_exporter",
    name: "Exportador de Talento",
    categoryId: "score_category.country_market",
    description: "High talent export profile.",
    metrics: [
      mr("metric.country_exports_per_season", 1.4),
      mr("metric.player_sales_per_season", 1.2),
      mr("metric.country_talent_depth_index", 1),
      mr("metric.transfer_profit_ratio", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_developer",
    name: "Formador",
    categoryId: "score_category.country_development",
    description: "Player development ecosystem profile.",
    metrics: [
      mr("metric.academy_output_index", 1.3),
      mr("metric.youth_minutes_pct", 1.2),
      mr("metric.country_talent_depth_index", 1.1),
      mr("metric.country_exports_per_season", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_technical",
    name: "Pais Tecnico",
    categoryId: "score_category.country_style",
    description: "Technical football identity profile.",
    metrics: [
      mr("metric.pass_completion_pct", 1.3),
      mr("metric.progressive_passes_per90", 1.1),
      mr("metric.xa_per90", 1),
      mr("metric.possession_pct", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_physical",
    name: "Pais Fisico",
    categoryId: "score_category.country_style",
    description: "Physical-intensity football profile.",
    metrics: [
      mr("metric.duel_win_pct", 1.4),
      mr("metric.pressures_per90", 1.1),
      mr("metric.goals_conceded_per90", 0.9),
      mr("metric.points_per_match", 0.8),
      mr("metric.clean_sheets_pct", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_tactical",
    name: "Pais Tatico",
    categoryId: "score_category.country_style",
    description: "Tactical maturity profile.",
    metrics: [
      mr("metric.tactical_flexibility_index", 1.3),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.pass_completion_pct", 1),
      mr("metric.competition_balance_index", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_offensive",
    name: "Pais Ofensivo",
    categoryId: "score_category.country_style",
    description: "Attack-output national profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.4),
      mr("metric.xg_per90", 1.1),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.country_talent_depth_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_defensive",
    name: "Pais Defensivo",
    categoryId: "score_category.country_style",
    description: "Defensive reliability national profile.",
    metrics: [
      mr("metric.goals_conceded_per90", 1.4),
      mr("metric.clean_sheets_pct", 1.2),
      mr("metric.duel_win_pct", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_emerging",
    name: "Pais Emergente",
    categoryId: "score_category.country_growth",
    description: "Rapidly growing football ecosystem profile.",
    metrics: [
      mr("metric.competition_surprise_index", 1.2),
      mr("metric.country_talent_depth_index", 1),
      mr("metric.reputation_index", 1),
      mr("metric.country_exports_per_season", 0.9),
      mr("metric.youth_minutes_pct", 0.8),
    ],
    contexts: countryContexts,
    modifiers: [...countryModifiers, mor("modifier.momentum_boost", 1)],
  }),
  countryScore({
    id: "score.country_declining",
    name: "Pais em Declinio",
    categoryId: "score_category.country_growth",
    description: "Downward legacy profile.",
    metrics: [
      mr("metric.title_count_index", 1),
      mr("metric.reputation_index", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
      mr("metric.country_talent_depth_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: [...countryModifiers, mor("modifier.decline_risk", 1.2)],
  }),
  countryScore({
    id: "score.country_breakout",
    name: "Pais Revelacao",
    categoryId: "score_category.country_growth",
    description: "Breakout cycle national profile.",
    metrics: [
      mr("metric.competition_surprise_index", 1.3),
      mr("metric.country_exports_per_season", 1),
      mr("metric.points_per_match", 0.9),
      mr("metric.reputation_index", 0.8),
      mr("metric.country_talent_depth_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: [...countryModifiers, mor("modifier.momentum_boost", 1)],
  }),

  countryScore({
    id: "score.country_elite_pipeline",
    name: "Pipeline de Elite",
    categoryId: "score_category.country_development",
    description: "Elite player production pipeline profile.",
    metrics: [
      mr("metric.academy_output_index", 1.3),
      mr("metric.country_talent_depth_index", 1.2),
      mr("metric.country_exports_per_season", 1),
      mr("metric.reputation_index", 0.9),
      mr("metric.youth_minutes_pct", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_domestic_stability",
    name: "Estabilidade Domestica",
    categoryId: "score_category.country_management",
    description: "Stable domestic ecosystem profile.",
    metrics: [
      mr("metric.competition_balance_index", 1.1),
      mr("metric.expected_points_per_match", 1),
      mr("metric.reputation_index", 1),
      mr("metric.financial_strength_index", 0.9),
      mr("metric.country_talent_depth_index", 0.8),
    ],
    contexts: [...countryContexts, cr("context.governance_stability", 1)],
    modifiers: [mor("modifier.consistency", 1.2), ...countryModifiers],
  }),
  countryScore({
    id: "score.country_financial_power",
    name: "Potencia Financeira",
    categoryId: "score_category.country_finance",
    description: "Financially strong ecosystem profile.",
    metrics: [
      mr("metric.financial_strength_index", 1.4),
      mr("metric.transfer_profit_ratio", 1),
      mr("metric.reputation_index", 1),
      mr("metric.country_exports_per_season", 0.8),
      mr("metric.continental_points", 0.8),
    ],
    contexts: [...countryContexts, cr("context.economic_context", 1)],
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_balanced",
    name: "Pais Equilibrado",
    categoryId: "score_category.country_style",
    description: "Balanced all-phase national profile.",
    metrics: [
      mr("metric.expected_points_per_match", 1.2),
      mr("metric.goals_scored_per90", 1),
      mr("metric.goals_conceded_per90", 1),
      mr("metric.pass_completion_pct", 0.9),
      mr("metric.duel_win_pct", 0.9),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_high_press",
    name: "Pais de Pressao Alta",
    categoryId: "score_category.country_style",
    description: "High pressing and intensity national profile.",
    metrics: [
      mr("metric.pressures_per90", 1.4),
      mr("metric.duel_win_pct", 1.1),
      mr("metric.goals_scored_per90", 0.9),
      mr("metric.goals_conceded_per90", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_counter_attacking",
    name: "Pais de Contra-Ataque",
    categoryId: "score_category.country_style",
    description: "Transition-heavy national profile.",
    metrics: [
      mr("metric.goals_scored_per90", 1.2),
      mr("metric.shots_on_target_pct", 1),
      mr("metric.pressures_per90", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.xg_per90", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_historic_legacy",
    name: "Legado Historico",
    categoryId: "score_category.country_historical",
    description: "Historical legacy national profile.",
    metrics: [
      mr("metric.title_count_index", 1.4),
      mr("metric.reputation_index", 1.3),
      mr("metric.continental_points", 1),
      mr("metric.financial_strength_index", 0.8),
      mr("metric.expected_points_per_match", 0.7),
    ],
    contexts: [...countryContexts, cr("context.era_weight", 1)],
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_tournament_specialist",
    name: "Especialista em Torneios",
    categoryId: "score_category.country_results",
    description: "Tournament cycle specialist profile.",
    metrics: [
      mr("metric.cup_win_rate", 1.3),
      mr("metric.points_per_match", 1),
      mr("metric.shots_on_target_pct", 0.9),
      mr("metric.goals_conceded_per90", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: [...countryModifiers, mor("modifier.big_matches", 1.1)],
  }),
  countryScore({
    id: "score.country_qualifier_specialist",
    name: "Especialista em Qualificacao",
    categoryId: "score_category.country_results",
    description: "Qualification phase optimization profile.",
    metrics: [
      mr("metric.points_per_match", 1.2),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.goals_scored_per90", 0.9),
      mr("metric.goals_conceded_per90", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_export_market",
    name: "Mercado Exportador",
    categoryId: "score_category.country_market",
    description: "Export-oriented football economy profile.",
    metrics: [
      mr("metric.country_exports_per_season", 1.4),
      mr("metric.player_sales_per_season", 1.2),
      mr("metric.transfer_profit_ratio", 1),
      mr("metric.academy_output_index", 0.8),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: [...countryContexts, cr("context.economic_context", 0.9)],
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_import_market",
    name: "Mercado Importador",
    categoryId: "score_category.country_market",
    description: "Import-heavy football economy profile.",
    metrics: [
      mr("metric.player_purchases_per_season", 1.3),
      mr("metric.financial_strength_index", 1.1),
      mr("metric.reputation_index", 1),
      mr("metric.points_per_match", 0.8),
      mr("metric.expected_points_per_match", 0.8),
    ],
    contexts: [...countryContexts, cr("context.economic_context", 0.9)],
    modifiers: countryModifiers,
  }),
  countryScore({
    id: "score.country_resurgent",
    name: "Pais em Ascensao",
    categoryId: "score_category.country_growth",
    description: "Resurgent macro trend profile.",
    metrics: [
      mr("metric.reputation_index", 1.1),
      mr("metric.expected_points_per_match", 1.1),
      mr("metric.competition_surprise_index", 1),
      mr("metric.country_talent_depth_index", 0.9),
      mr("metric.points_per_match", 0.8),
    ],
    contexts: countryContexts,
    modifiers: [...countryModifiers, mor("modifier.momentum_boost", 1.1)],
  }),
  countryScore({
    id: "score.country_data_driven",
    name: "Pais Data-Driven",
    categoryId: "score_category.country_management",
    description: "Data-informed national setup profile.",
    metrics: [
      mr("metric.expected_points_per_match", 1.3),
      mr("metric.tactical_flexibility_index", 1),
      mr("metric.pass_completion_pct", 1),
      mr("metric.country_talent_depth_index", 0.9),
      mr("metric.reputation_index", 0.8),
    ],
    contexts: countryContexts,
    modifiers: [mor("modifier.data_quality_flag", 1), ...countryModifiers],
  }),
];
